frames = 300
views = 5

default_pattern = "frame#%03d.png"

[cases]
vtm_types = ["AI", "RA"]
seqs = []

[path]
input = ""
output = ""

[app]
ffmpeg = "ffmpeg"
encoder = "EncoderApp"
preproc = "mca-preproc"
postproc = "mca-postproc"
rlc = "RLC40"

[QP.anchor]
"TBD" = []

[QP.wMCA]
"TBD" = []

[pipeline]
"NagoyaFujita" = 0
"NagoyaOrigami" = 0
"Tunnel_Train" = 0
"TempleBoatGiantR32" = 0
"Boys" = 1
"Motherboard" = 1
"MiniGarden" = 1
"HandTools" = 1
